const requireALot = require('../../src')
const path = require('path')
module.exports = requireALot(require)(
  '../lib/capture', 'assert', 'cowlog', '../../src', 'require-dir', 'path', 'generic-text-linker')
  .from('chai', ['expect'])
  // .from('genericTextLinker',['linkerDir'])
  .alias('../../src', 'requireALot')
  .information('requireALot', 'The main library itself.')
  .linkDirectory(path.join(__dirname, '../', 'tests'))
  .log.info.tag('testRequires')
  .removeUnused()
