const requireALot = require('../../src')
const path = require('path')
module.exports = requireALot(require)('../lib/capture','assert', 'cowlog')
// .from('chai',['expect'])
//   .log.info.tag("testIncludes")
// .alias('src', 'requireALot')
  .linkDirectory(path.join(__dirname, '../', 'tests'))()
